version: "3"
services:

  app:
    build: app
    container_name: com.recorder.api
    restart: always
    expose:
      - 5000
    volumes:
      - ./app:/app/code

  proxy:
    build: proxy
    container_name: com.recorder.proxy
    restart: always
    ports: 
      - 8080:80

volumes:
  app_data: {}

networks:
  default:
    name: shift_recorder_network