version: "3"

services:

  jenkins:
    build: jenkins
    container_name: com.ci_cd.jenkins
    restart: always
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9090:8080
    
  private_registry:
    build: private_registry
    container_name: com.registry.docker
    restart: always
    ports:
      - 9002:5000
    volumes:
      - private_registry_data:/registry-data 

  sonarqube:
    build: sonar_qube
    container_name: com.code_analysis.sonarqube
    restart: always
    depends_on:
      - sonarqube_db
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:9001/sonarqube
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - 9000:9000
    expose:
      - 9000

  sonarqube_db:
    build: sonarqube_db
    container_name: sonarqube_db
    volumes:
      - sonarqube_database:/var/lib/postgresql
      - sonarqube_database_data:/var/lib/postgressql/data
    ports:
      - 9001:5432

volumes:
  jenkins_data: {}
  private_registry_data: {}
  sonarqube_database_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_database:
  sonarqube_extensions:

networks:
  default:
    name: ci_cd_network
