
version: "3"

services:
  ansible:
    build: ansible
    container_name: com.provision.ansible
    restart: always
    volumes:
      - ./ansible:/temps
    stdin_open : true
    tty: true

networks:
  default:
    name: ci_cd_network
